### ISSUE TITLE
Initialize the development environment with Docker

### ISSUE THREAD

**Issue by yaroyan** [yaroyan/automatic-cryptocurrency-trader-go#1]
### TODO

- [x] Create a container for the minimum required services for this system.
- [x] Create a general user.
- [x] Make the UID/GID of general users the same as the host.
